import Profile from "../../models/profile";

module.exports = (data: Profile) => ({
  info: {
    tune_cnt: K.ITEM("s32", data?.qubell?.tuneCount || 0),
    clear_cnt: K.ITEM("s32", data?.qubell?.clearCount || 0),
    fc_cnt: K.ITEM("s32", data?.qubell?.fcCount || 0),
    ex_cnt: K.ITEM("s32", data?.qubell?.exCount || 0),
    match_cnt: K.ITEM("s32", data?.qubell?.matchCount || 0),
    total_best_score: K.ITEM("s32", data?.qubell?.totalBestScore || 0),
    extra_point: K.ITEM("s32", data?.qubell?.extraPoint || 0),
    is_extra_played: K.ITEM("bool", data?.qubell?.isExtraPlayed || false),
    clear_max_level: K.ITEM("s16", data?.qubell?.clearMaxLevel || 0),
    fc_max_level: K.ITEM("s16", data?.qubell?.fcMaxLevel || 0),
    ex_max_level: K.ITEM("s16", data?.qubell?.exMaxLevel || 0),
    jubility: K.ITEM("s16", data?.qubell?.jubility || 0),
    jubility_yday: K.ITEM("s16", data?.qubell?.jubilityYday || 0),
  },
  last: {
    music_id: K.ITEM("s32", data?.musicId || 0),
    seq_id: K.ITEM("s8", data?.seqId || 0),
    play_time: K.ITEM("s64", data?.lastPlayTime || BigInt(0)),
    shopname: K.ITEM("str", data?.lastShopname || ""),
    areaname: K.ITEM("str", data?.lastAreaname || ""),
    marker: K.ITEM("s8", data?.qubell?.marker || 0),
    theme: K.ITEM("s8", data?.qubell?.theme || 0),
    title: K.ITEM("s16", data?.qubell?.title || 0),
    parts: K.ITEM("s16", data?.qubell?.parts || 0),
    sort: K.ITEM("s8", data?.qubell?.sort || 0),
    category: K.ITEM("s8", data?.qubell?.category || 0),
    expert_option: K.ITEM("s8", data?.qubell?.expertOption || 0),
    matching: K.ITEM("s8", data?.qubell?.matching || 0),
    hazard: K.ITEM("s8", data?.qubell?.hazard || 0),
    hard: K.ITEM("s8", data?.qubell?.hard || 0),
    last_course_id: K.ITEM("s32", data?.qubell?.lastCourseId || 0),
  },
  item: {
    secret_list: K.ARRAY("s32", data?.qubell?.secretList || Array(32).fill(-1)),
    theme_list: K.ITEM("s32", data?.qubell?.themeList || -1),
    marker_list: K.ARRAY("s32", data?.qubell?.markerList || Array(2).fill(-1)),
    title_list: K.ARRAY("s32", data?.qubell?.titleList || Array(96).fill(-1)),
    parts_list: K.ARRAY("s32", data?.qubell?.partsList || Array(96).fill(-1)),
    secret_list_new: K.ARRAY("s32", data?.qubell?.secretListNew || Array(32).fill(0)),
    theme_list_new: K.ITEM("s32", data?.qubell?.themeListNew || 0),
    marker_list_new: K.ARRAY("s32", data?.qubell?.markerListNew || Array(2).fill(0)),
    title_list_new: K.ARRAY("s32", data?.qubell?.titleListNew || Array(96).fill(0)),
  },
  course: {
    last_course_id: K.ITEM("s32", data?.qubell?.lastCourseId || 0),
  },
});
